spring:
    application:
        name: iot-vmp-vmanager
        # 影子数据存储方式，支持redis、jdbc,暂不支持mysql
        database: redis
        # 通信方式，支持kafka、http
        communicate: http
    redis:
        # Redis服务器IP
        host: 127.0.0.1
        #端口号
        port: 6379
        database: 6
        #访问密码,若你的redis服务器没有设置密码，就不需要用密码去连接
        password:
        #超时时间
        timeout: 10000
    datasource: 
        name: eiot
        url: jdbc:mysql://127.0.0.1:3306/eiot?useUnicode=true&characterEncoding=UTF8&rewriteBatchedStatements=true
        username:
        password:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver

server:
    port: 6060
    ssl:
      # SSL 证书路径，classpath 必不可少
      key-store: classpath:4975710_wvp.shuolian18.com.pfx
      # SSL 证书密码
      key-store-password: 2lngfj26
      # 证书类型
      key-store-type: PKCS12

sip:
    ip: 192.168.20.111
    port: 5060
    # 根据国标6.1.2中规定，domain宜采用ID统一编码的前十位编码。国标附录D中定义前8位为中心编码（由省级、市级、区级、基层编号组成，参照GB/T 2260-2007）
    # 后两位为行业编码，定义参照附录D.3
    # 3701020049标识山东济南历下区 信息行业接入
    domain: 1401091149
    id: 14010911492007000001
    # 默认设备认证密码，后续扩展使用设备单独密码
    password: shuolian18

auth: #32位小写md5加密（默认密码为admin）
    username: admin
    password: 21232f297a57a5a743894a0e4a801fc3

media: #zlm服务器的ip与http端口, 重点: 这是http端口
    ip: 192.168.18.56 # 如果zlm与wvp在同一台服务器,可以设置为127.0.0.1, 若不是同一台服务器,则配置内网ip
    port: 80
    wanIp:  # zlm所在服务器的公网IP
    internetIp: md.shuolian18.com # zlm所在服务器的公网IP
    internetPort: 7776 # zlm所在服务器的公网IP
    secret: 035c73f7-bb6b-4889-a715-d9eb2d1925cc
    streamNoneReaderDelayMS:  10000  # 无人观看多久自动关闭流
    # 关闭等待收到流编码信息后在返回,
    # 设为false可以获得更好的兼容性,保证返回后流就可以播放,
    # 设为true可以快速打开播放窗口,可以获得更好的体验
    closeWaitRTPInfo: true
    rtp: # 启用udp多端口模式
        enable: true
        udpPortRange: 30000,30500 # 端口范围
logging:
    file:
        name: logs/wvp.log
        max-history: 30
        max-size: 10MB
        total-size-cap: 300MB
    level:
        com:
            genersoft:
                iot: debug